- become: yes
  hosts: all
  name: Streaming Setup
  roles:
    - geerlingguy.docker

  tasks:
    - name: Add SSH key 
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', pub_key) }}"

    - name: Update all packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    # - name: Install aptitude using apt
    #   apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
 
    # - name: Install required system packages
    #   apt: name={{ item }} state=latest update_cache=yes
    #   loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
 
    # - name: Add Docker GPG apt Key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present
 
    # - name: Add Docker Repository
    #   apt_repository:
    #     repo: deb https://download.docker.com/linux/ubuntu bionic stable
    #     state: present
 
    # - name: Update apt and install docker-ce
    #   apt: update_cache=yes name=docker-ce state=latest

    # - name: Copy Private key
    #   copy:
    #     src: files/stream_rsa
    #     dest: ~/.ssh
    
    # - name: Copy Private key
    #   copy:
    #     src: files/stream_rsa.pub
    #     dest: ~/.ssh
