- become: yes
  hosts: all
  name: Streaming Setup
  # roles:
  #  - geerlingguy.docker

  tasks:
    # - name: Add SSH key 
    #   authorized_key:
    #     user: root
    #     state: present
    #     key: "{{ lookup('file', pub_key) }}"

    # - name: Ensure .ssh directory exists.
    #   file:
    #     path: /root/.ssh
    #     state: directory
    #     mode: 0700

    # - name: Ensure GitHub deploy key is present on the server.
    #   copy:
    #     content: "{{ lookup('file', pvt_key) }}"
    #     dest: /root/.ssh/id_rsa
    #     mode: 0600
    
    # See: https://stackoverflow.com/a/37096534/100134
    # - name: Ensure setfacl support is present.
      # package: name=acl

    # - name: Clone the code repository to the docroot.
    #   git:
    #     repo: "https://github.com/Creeds-Streaming/streaming-infrastructure-experimental.git"
    #     dest: ~/data
    #     accept_hostkey: yes
    #     key_file: ~/.ssh/deploy_key
        
    - name: Display the config
      debug:
        msg: "Hello World"